#!/bin/zsh

IDENTIFIER="#__322209919_BLCKINSTUNINSTIDENTIFIER"
END_IDENTIFIER="#__END_322209919_BLCKINSTUNINSTIDENTIFIER"

register_txt="#__322209919_BLCKINSTUNINSTIDENTIFIER Do not modify anything on this line or the next! This will prevent
#proper uninstallation and/or updation of blck. This identifier was made by blck.

#-------------------------------------#
# blck Configuration - Autogenerated  #
#-------------------------------------#

BLCK_HOME="/home/therdas/.blck"
[ ! -e "$BLCK_HOME/blck.sh" ] || source $BLCK_HOME/blck.sh
[ ! -e "$BLCK_HOME/blck.sh" ] && echo \"Could not locate blck. Please clean up your .zshrc file.\"

#-------------------------------------#
#__END_322209919_BLCKINSTUNINSTIDENTIFIER You can continue after this line"

is-installed() {
    txt=$(eval sed -n \'/$IDENTIFIER\.\*\$/,/$END_IDENTIFIER\.\*\$/\{p\}\' $HOME/\.zshrc)
    echo "Found installation: "
    echo "$txt"
}

uninstall() {
    txt=$(eval sed \'/$IDENTIFIER\.\*\$/,/$END_IDENTIFIER\.\*\$/\{d\}\' $HOME/\.zshrc)
    echo "$txt" > $HOME/.zshrc
}

install() {
    echo register_txt >> $HOME/.zshrc
}

remove-installed